Maxim work banch
frontend-park-mail-ru/2021_1_Fyvaoldzh pull request #11
Opened 2021-03-25 21:22 UTC by PurpleLime

2021-03-28 20:39 UTC, n-merkulova requested changes
почти все замечания, которые я указала, относятся ко всему проекту в целом. нужно перепроверить код и отрефачить)

2021-03-28 20:39 UTC, n-merkulova commented on .eslintignore
> -node_modules
лучше это было бы оставить

2021-03-28 20:39 UTC, n-merkulova commented on .eslintrc
> -  }
поч удалили этот файл?(

2021-03-28 20:39 UTC, n-merkulova commented on .prettierrc
> -}
а этот почему?

2021-03-28 20:39 UTC, n-merkulova commented on package.json
> -  },
это не удалось починить?

2021-03-28 20:39 UTC, n-merkulova commented on public/components/css/buttons.css
> +  font-family: PT Serif;
этот шрифт стоит на всем сайте, достаточно поставить его на body. кроме того, хорошо бы еще прописать дефолтный шрифт так: `font-family: PT Serif, sans-serif`

2021-03-28 20:39 UTC, n-merkulova commented on public/components/css/buttons.css
> +  font-family: PT Serif;
то же самое замечание с шрифтами

2021-03-28 20:39 UTC, n-merkulova commented on public/components/css/form.css
> +  font-family: PT Serif;
шрифты

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar-logged.js
> +pug_html = pug_html + "\u003Ca class=\"navbar-profile-name\" href=\"#\" data-direction=\"profile\"\u003E";
! этих файлов не должно быть на гите

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  background: url("img/signup.svg") no-repeat center / 100%;
лучше прописывать относительные пути. 100% писать ну нужно, лучше писать так: `background: url("img/signup.svg") no-repeat center / cover`

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  background: url("img/logout.svg") no-repeat center / 100%;
то же замечание про пути и проценты, что выше

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  font-weight: normal;
шрифты + `font-style: normal` и `font-weight: normal` прописывать не нужно, это дефолтное значение

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
>    background: url("img/avatar.jpeg") no-repeat center / 100%;
прогугли, что именно ты делаешь такой сокращенной записью, когда пишешь 100%. если так заимствовано у Димы, скажи и ему тоже

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +.dropdown-menu__logout {
`.dropdown-menu__logout`, `.dropdown-menu__events` абсолютно одинаковые, дублируют стили. `.dropdown-menu__settings` почти что тоже. можно записывать такое короче просто селекторами через запятую (`.dropdown-menu__logout, .dropdown-menu__events`)

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  font-weight: normal;
см замечания про шрифты выше

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  background: url("img/logout.svg") no-repeat center / cover;
относительные пути

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  margin-left: 11px;
для margin можно просто короткую запись использовать

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  float: left;
ппц, тебе точно это нужно? это уже очень старые стили, как верстка на таблицах, такое не используется нигде)

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  background: url("img/events.svg") no-repeat center / cover;
пути + снова дублируются стили с `.dropdown-menu__logout:before`

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  background: url("img/settings.svg") no-repeat center / cover;
снова пути и дублирование стилей(

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +[class^='dropdown-menu__']:hover {
шок, это что?

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.css
> +  background: url("img/dropdown.svg") no-repeat center / cover;
пути

2021-03-28 20:39 UTC, n-merkulova commented on public/components/navbar/navbar.js
> +pug_html = pug_html + "\u003Ca" + (" class=\"logo\""+" href=\"\u002F\" data-direction=\"main\""+pug_attr("data-profileId", Uid, true, false)) + "\u003E";
удалить этот файл

2021-03-28 20:39 UTC, n-merkulova commented on public/js/initialModule/initial.js
> +import {renderMyProfilePage} from '../renderModule/render.js';
не нужно писать в названии `module`. а еще можно делать сразу несколько импортов из одного файла: `import {renderProfilePage, renderMyProfilePage} from '../renderModule/render.js';`

2021-03-28 20:39 UTC, n-merkulova commented on public/js/initialModule/initial.js
> +import {renderLoggedNavbar} from '../renderModule/render.js';
мне не нравится такая разбивка на модули. почему модуль называется initial? что он означает? почему он в корне папки js, а не в libs? почему render не в libs тоже?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +import {postLoginData} from './networkModule/network.js';
почему вы не делаете сразу несколько импортов в одной строке?((

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +const wrapper = document.getElementById('wrapper'); //почему document находит index.html??????
все твои скрипты подгружаются в твоем index.html и исполняются в браузере, то есть имеют доступ к объекту window, полем которого является document

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +import {urlMap} from '../js/initialModule/initial.js';
! все импорты должны быть наверху, не посреди кода

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +  //тут часть валидации типо?????????
типо да, нужно убрать)

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +  const {target} = e; //target = e.target??????????????????????????????????
это деструктуризация. да, это равносильные записи

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +  /*if (Object.prototype.toString.call(target) !== '[object HTMLInputElement]') {
почему закоменчено?(

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +      let dataFromForm = new FormData(formBody);
зачем заменил на let?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +        let jsonData = JSON.stringify(Object.fromEntries(dataFromForm));
зачем заменил на let?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +        let answer = await postRegistationData(jsonData);
зачем заменил на let?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +      let dataFromForm = new FormData(formBody);
зачем заменил на let?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +        let jsonData = JSON.stringify(Object.fromEntries(dataFromForm));
зачем заменил на let?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +        let answer = await postLoginData(jsonData);
зачем заменил на let?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +        console.log(answer);
не забывай удалять логи

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +      let dataSpanForm = new FormData(target.parentNode);
ну почему же везде заменил на let?((( в чем разница let и const? как ведут себя константные объекты?

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +        console.log(formPut);
логи(

2021-03-28 20:39 UTC, n-merkulova commented on public/js/main.js
> +          let avaProfile = document.getElementById('profileAvatar');
отчислю, если не выяснишь, когда использовать let, а когда const

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> +  return jsonFile;
сразу `return await fetch(allEventsUrl)?.json()`

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> +  console.log(jsonFile);
логи. и тоже можно сразу записать return без лишних переменных

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> + * @return {json} - json профиля
блестяще, а как насчет остальным функциям дописать jsdoc?))

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> +  return jsonFile;
все те же замечания, что выше

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> +  let answer = await fetch(postRegistrationDataUrl, {
const

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> +  let answer = await fetch(postLoginDataUrl, {
const, опять логи

2021-03-28 20:39 UTC, n-merkulova commented on public/js/networkModule/network.js
> +  let answer = await fetch(currentProfileUrl, {
все замечания, что выше

2021-03-28 20:39 UTC, n-merkulova commented on public/js/renderModule/render.js
> +// import * as url from "url";
а это что???

2021-03-28 20:39 UTC, n-merkulova commented on public/templates/login/login.js
> +pug_html = pug_html + "\u003Cdiv class=\"form-body__error_input\" id=\"loginError\"\u003E\u003C\u002Fdiv\u003E";
удоли

2021-03-28 20:39 UTC, n-merkulova commented on public/templates/one-event-block/one-event-block.html
> +            <a href="#" data-direction="eventPage">Какая-то очень красивая интересная выставка</a>
почему у нас еще остаются html?

2021-03-28 20:39 UTC, n-merkulova commented on public/templates/one-event-block/smbs-events.css
> +    margin: 25px 25px 25px 0px;
короткая запись

2021-03-28 20:39 UTC, n-merkulova commented on public/templates/profile/profile.css
> +/*.profile-header__avatar::before {*/
почему тут комент?(

2021-03-29 18:23 UTC, PurpleLime commented on .prettierrc
> -}
гитигнор

2021-03-29 18:25 UTC, PurpleLime commented on public/components/navbar/navbar.css
>    background: url("img/avatar.jpeg") no-repeat center / 100%;
это не мой код

2021-03-29 18:35 UTC, PurpleLime commented on public/templates/profile/profile.css
> +/*.profile-header__avatar::before {*/
потому что это херня не работает

2021-04-01 09:38 UTC, closed without merging